### ISSUE TITLE
Error message for "long" alleles

### ISSUE THREAD

**Issue by sgagliano** [welchr/swiss#1]
_Current message like this:_ 
Warning: variant alleles are too long for PLINK 1.9, skipping (truncated alleles to first 10 bp): 5:45949658_CTGAGAAACT.../C...
_Maybe, make more clear._

**Comment by welchr** [comment]
Yes, this needs at least a better error message, or a fix for this issue of missing indels that have very long allele strings...

Which LD source were you using? If it was one of your own VCFs, could you provide the path to the file on our cluster? Also the command line used?

**Comment by sgagliano** [comment]
I just used your default LD source, which I believe is `1000G_2012-03_EUR`
My command line script is here `/net/wonderland/home/csidore/Epacts_vcfs/Michelle_panel/GOODheader/R2sameasPapers/SWISS.sh`
