### ISSUE TITLE
Is there a way to run SWISS without needing the MARKER_ID column?

### ISSUE THREAD

**Issue by jdarias93** [welchr/swiss#12]
#### Command-line used to cause the issue
```
swiss --assoc ASSET.SWISS.chr22.txt --pval-col "PVALUE" --out ASSET.SWISS.chr22 --dist-clump --clump-p 5e-9 --clump-dist 1000000
```

#### Problem description

Please describe the issue: 

* What is the problem? 
Is there are way to perform a SWISS analysis without having the Marker_ID column? I just want to sift out SNPs within +/- 1MB windows.
* Is it reproducible? 
Yes

#### Program output

* What did the program output? Was there an error message?
```
Loading results file: ASSET.SWISS.chr22.txt
Traceback (most recent call last):
  File "/usr/cluster/bin/swiss", line 20, in <module>
    main()
  File "/net/mario/cluster/boehnke/bin/welchr/swiss_dev/local/lib/python2.7/site-packages/swiss/main.py", line 1074, in main
    run_process(opts.assoc,opts.trait,opts.out,opts)
  File "/net/mario/cluster/boehnke/bin/welchr/swiss_dev/local/lib/python2.7/site-packages/swiss/main.py", line 799, in run_process
    results.load(sep=opts.delim)
  File "/net/mario/cluster/boehnke/bin/welchr/swiss_dev/local/lib/python2.7/site-packages/swiss/AssocResults.py", line 233, in load
    chrom, pos, ref, alt, _ = parse_epacts(variant)
  File "/net/mario/cluster/boehnke/bin/welchr/swiss_dev/local/lib/python2.7/site-packages/swiss/utils.py", line 96, in parse_epacts
    raise ValueError("No ref/alt alleles found in EPACTS ID " + v)
ValueError: No ref/alt alleles found in EPACTS ID 22:18123678
```

#### Swiss version

If you don't know your swiss version, please do: 

```bash
swiss --version
```
Says 1.0.0 but I think it's version 1.0.1 (with the extreme p-value fix).

**Comment by welchr** [comment]
Unfortunately no, swiss needs to identify each variant uniquely (for merging with LD data and GWAS catalog hits.) 

In the above error, it looks like you've already got chromosome and position, so you would only need to get the ref and alt alleles and add those on. The variant ID should look like "CHR:POS_REF/ALT".

**Comment by jdarias93** [comment]
Thank you, Dr. Welch!

**Comment by welchr** [comment]
No problem. One thing to add would be that if you need to figure out which allele is REF and which is ALT, you could use dbSNP's VCFs which are available to download at: https://ftp.ncbi.nih.gov/snp/latest_release/

Regards, 

Ryan
