### ISSUE TITLE
hg 38 support

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [welchr/swiss#17]
Can you tell me when the hg38 support will be available? TIA

**Comment by welchr** [comment]
There should be support for GRCh38 - you may need to rerun `swiss-create-data` to get the new catalogs. Make sure to use `--dbsnp-build b151` - the default is b141, but NCBI removed the file for it from their server (#15).

**Comment by Mahantesh-Biradar** [comment]
Thanks for your update!
