### ISSUE TITLE
Order summary statistics by p-value

### ISSUE THREAD

**Issue by giuliapontali** [welchr/swiss#20]
Hi, 

I was wondering if the input file for swiss should be sorted by p-value, from smallest to largest. 
If we pass summary statistics as input as is (without any sorting) do we get different results? 
What do you suggest we do?

Thanks a lot!

**Comment by welchr** [comment]
I have not used or worked on this program in many years, but my recollection is that it should not matter how the input is sorted, the program will internally sort the input by p-value and the output should reflect that. To confirm, you could randomly permute your input and see if that has any effect on swiss output.
