### ISSUE TITLE
Independent hits that are known GWAS variants do not appear in ld-gwas

### ISSUE THREAD

**Issue by welchr** [welchr/swiss#6]
Currently each independent hit's LD buddies will be checked if they are known GWAS variants, but the independent hit itself is not. 

Will patch by either including the independent hit as an LD buddy with r2=1 or will just directly check each independent hit in the catalog.

**Comment by welchr** [comment]
This should be fixed by 3cbab1c. Test case added and it passes. Just waiting for user who reported the issue to confirm this also works for them.

**Comment by mmoisse** [comment]
It creates an other minor issue
```
$ swiss --download-data
Created data directory: ~/.local/share/swiss/
Error: Failed to download data version from https://portaldev.sph.umich.edu/swiss/swiss_data_1.0.0b5.dev1.version
```

**Comment by welchr** [comment]
Linked that file on the server, should work now. I wasn't expecting you would need to re-download the data, though. Are you unable to run swiss without doing --download-data? You should be able to install this right over your existing (or that's the idea, anyway.)

**Comment by mmoisse** [comment]
On one computer the data was not installed yet, so I needed the --download-data command.
But for the rest it worked nicely, the trick to get it installed was to use the --user flag, otherwise it would say everything was fine but we were still left with the old unpatched version
```
pip install --no-deps -I --force-reinstall --user git+https://github.com/welchr/swiss.git@bug/indep-hit-self-gwas 
```
